default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: 
  password:

development:
  <<: *default
  database: db_development

test:
  <<: *default
  database: db_test

production:
  <<: *default
  database: db_production
  username: 
  password:

